UART<->WiFi fixes
* Was spamming the log output with the following error message when
  no Telnet connection had been made to port 2332 and the target was
  transmitting bytes from its UART:
   error: socket_server.cpp:223 send() - UART<->WiFi socket has been
          closed so ## bytes have been discarded.
  I added a virtual discardingBytesDueToUnconnectedSocket() method to
  socket server classes that gets called when such discarding is
  occurring. For GDBServer this still logs as an error and for
  UartWiFiBridge it is just logged as debug output that is only shown
  when verbose logging is enabled.
* UART<->WiFi was losing bytes that should have been sent from the
  target to the host over WiFi. This was caused by UART Rx FIFO
  overflow. I modified the UART code to run at a higher priority than
  the networking code and just place received UART data into a circular
  buffer and then pend an async call to be run at a lower priority for
  actually submitting the data to the lwIP network stack. This stops
  the UART handler from getting stalled by other ISRs or tcp_send()
  calls.
* After making the above fix, I was able to modify
  UartWiFiBridge::shouldSendNow() to ask the lwIP networking stack to
  send any buffered up data if it contains a '\n' character. This
  makes it more appropriate for interactive I/O.

I also updated the build version to 0.6-20240908.0 since this build
will become the new LKG.